swagger: '2.0'
info:
  title: APIGateway
  description: APIGateway for endpoints
  version: 1.0.0
host: endpoint-rbiyrqzyqa-an.a.run.app
securityDefinitions:
  api_key:
    type: apiKey
    name: key
    in: query
schemes:
  - https
produces:
  - application/json
x-google-backend:
  address: https://vision-rbiyrqzyqa-an.a.run.app
paths:
  /:
    get:
      summary: health check
      operationId: root
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /image2words:
    post:
      summary: image2words
      operationId: image2words
      responses:
        '200':
          description: A successful response
          schema:
            type: string
      security:
        - api_key: []
  /image2lines:
    post:
      summary: image2lines
      operationId: image2lines
      responses:
        '200':
          description: A successful response
          schema:
            type: string
      security:
        - api_key: []
  /image2texts:
    post:
      summary: image2texts
      operationId: image2texts
      responses:
        '200':
          description: A successful response
          schema:
            type: string
      security:
        - api_key: []
  /pdf2lines:
    post:
      summary: pdf2lines
      operationId: pdf2lines
      responses:
        '200':
          description: A successful response
          schema:
            type: string
      security:
        - api_key: []
